// Circuit Codex — content data
// Mirrors the consolidated reference document. Each domain has sub-sections
// with tools. Tools with `calc: "id"` open a working calculator screen;
// all others open a placeholder "coming soon" screen.

const DOMAINS = [
  {
    id: "passive",
    title: "Passive components",
    subtitle: "Resistors, capacitors, coils",
    color: "#5B9BE0",
    bg: "#1B2A3B",
    icon: "resistor",
    sections: [
      {
        title: "Resistors",
        tools: [
          { name: "Resistor color code", was: "Color code", calc: "resistor-color-code" },
          { name: "Resistor SMD code", was: "SMD code", calc: "smd-code" },
          { name: "Resistor power rating", was: "Power rating", calc: "resistor-power-rating" },
          { name: "E-series values", was: "E-series value", calc: "e-series" },
          { name: "Series/parallel (R)", was: "Series/parallel", calc: "series-parallel" },
          { name: "Voltage divider", calc: "voltage-divider" },
          { name: "Current divider", calc: "current-divider" },
          { name: "Wheatstone bridge", calc: "wheatstone-bridge" },
          { name: "Delta-Y transform", calc: "delta-y" },
          { name: "NTC/PTC thermistor", calc: "thermistor" },
        ],
      },
      {
        title: "Capacitors",
        tools: [
          { name: "Ceramic cap code", was: "Ceramic code", calc: "ceramic-code" },
          { name: "Film capacitor code", was: "Film code", calc: "film-code" },
          { name: "Capacitor SMD code", was: "SMD code", calc: "cap-smd-code" },
          { name: "Series/parallel (C)", was: "Series/parallel", calc: "cap-series-parallel" },
          { name: "RC charge/discharge", was: "Charge/discharge (RC)", calc: "rc-charge" },
          { name: "Capacitor energy", was: "Stored energy", calc: "cap-stored-energy" },
        ],
      },
      {
        title: "Inductors",
        tools: [
          { name: "Inductor color code", was: "Color code", calc: "inductor-color-code" },
          { name: "Inductor SMD code", was: "SMD code", calc: "inductor-smd-code" },
          { name: "Air-core coil (Wheeler)" },
          { name: "Toroid winding" },
          { name: "Transformer (turns ratio)" },
          { name: "Series/parallel (L)" },
          { name: "Toroid/ferrite reference table" },
        ],
      },
      {
        title: "Passive filters",
        tools: [
          { name: "RC filter", calc: "rc-filter" },
          { name: "RL filter", calc: "rl-filter" },
          { name: "LC filter (band-pass/notch)" },
          { name: "RLC filter" },
        ],
      },
      {
        title: "Reference",
        tools: [{ name: "SMD package sizes", calc: "smd-package-sizes" }],
      },
    ],
  },
  {
    id: "active",
    title: "Active & semiconductor devices",
    subtitle: "Diodes, transistors, op-amps",
    color: "#B98FE0",
    bg: "#2A1B32",
    icon: "transistor",
    sections: [
      { title: "Diodes", tools: [{ name: "Diode forward voltage", was: "Forward voltage / biasing", calc: "diode-biasing" }, { name: "Zener regulation" }, { name: "LED series resistor", calc: "led-series-resistor" }] },
      { title: "Transistors (BJT)", tools: [{ name: "BJT biasing (voltage divider)", was: "Biasing (voltage divider bias)", calc: "transistor-bias" }, { name: "BJT as a switch", was: "NPN/PNP as a switch", calc: "transistor-switch" }, { name: "BJT currents (hFE, IC)", was: "Example calculation (hFE, IC)", calc: "transistor-example" }] },
      { title: "MOSFET / IGBT", tools: [{ name: "MOSFET biasing", was: "Biasing", calc: "mosfet-bias" }, { name: "MOSFET switching", was: "Switching calculation", calc: "mosfet-switch" }] },
      { title: "Rectifiers", tools: [{ name: "Half-wave rectifier", was: "Half-wave", calc: "rectifier-halfwave" }, { name: "Bridge rectifier", was: "Full-wave (bridge)", calc: "rectifier-bridge" }, { name: "Center-tap rectifier", was: "Full-wave with center tap", calc: "rectifier-centertap" }, { name: "Rectifier ripple", was: "Half-wave with capacitor (ripple)", calc: "rectifier-halfwave-cap" }] },
      { title: "Thyristors (SCR, TRIAC) & MOSFET", tools: [{ name: "AC phase control", was: "Firing angle basics", calc: "thyristor-firing" }] },
      {
        title: "Op-amps",
        tools: [
          { name: "Inverting amp", was: "Inverting amplifier", calc: "opamp-inverting" }, { name: "Non-inverting amp", was: "Non-inverting amplifier", calc: "opamp-noninverting" }, { name: "Buffer", was: "Buffer (voltage follower)", calc: "opamp-buffer" },
          { name: "Comparators", was: "Comparator (± hysteresis / Schmitt trigger)", calc: "opamp-comparator" }, { name: "Op-amp integrator", was: "Integrator", calc: "opamp-integrator" }, { name: "Op-amp differentiator", was: "Differentiator", calc: "opamp-differentiator" },
          { name: "Summing amplifier", calc: "opamp-summing" }, { name: "Differential amplifier", calc: "opamp-differential" }, { name: "Sallen-Key filter" },
        ],
      },
      { title: "Optoelectronics", tools: [{ name: "Photocell / LDR", calc: "photocell-ldr" }, { name: "Optocoupler", calc: "optocoupler" }, { name: "Light wavelength ↔ color", was: "Wavelength ↔ color/spectrum chart", calc: "spectrum-chart" }] },
    ],
  },
  {
    id: "digital",
    title: "Digital & logic circuits",
    subtitle: "Gates, flip-flops, binary",
    color: "#5DCAA5",
    bg: "#1F3B33",
    icon: "binary",
    sections: [
      { title: "Logic gates", tools: [{ name: "Basic gates (AND, OR, NOT, NAND, NOR, XOR, XNOR)", calc: "logic-gates" }, { name: "Karnaugh map simplification", calc: "karnaugh" }] },
      { title: "Sequential logic", tools: [{ name: "Flip-flops (SR, D, JK, T)", calc: "flip-flops" }, { name: "Multivibrators (astable/monostable)", calc: "multivibrator" }, { name: "555 Timer (astable/monostable)", calc: "555-timer" }] },
      { title: "Number systems", tools: [{ name: "DEC / HEX / OCT / BIN conversion", calc: "dec-hex-bin" }, { name: "ASCII table", calc: "ascii-table" }] },
      {
        title: "Timing & interfaces",
        tools: [
          { name: "PWM (duty cycle)", calc: "pwm-duty" }, { name: "Debounce / RC timing", calc: "debounce-rc" }, { name: "I2C pull-up resistor", calc: "i2c-pullup" }, { name: "UART baud rate", calc: "uart-baud" },
          { name: "Crystal load capacitance", calc: "crystal-load" }, { name: "Oscillator stability (ppm → Hz)", calc: "osc-stability" }, { name: "PLL multiplication factor", calc: "pll" },
        ],
      },
      { title: "Data conversion", tools: [{ name: "ADC resolution / quantization", calc: "adc" }, { name: "DAC resolution", calc: "dac" }, { name: "SNR estimation", calc: "snr" }] },
    ],
  },
  {
    id: "rf",
    title: "RF & microwave",
    subtitle: "Radio, antennas, wireless",
    color: "#E08585",
    bg: "#3B1E22",
    icon: "antenna",
    sections: [
      { title: "Antennas & propagation", tools: [{ name: "Path loss" }, { name: "Wavelength ↔ frequency", was: "Wavelength", calc: "wavelength" }, { name: "Beamwidth & gain" }, { name: "Fresnel zone" }, { name: "Antenna length (dipole/monopole)" }] },
      { title: "Transmission lines", tools: [{ name: "VSWR / Return loss" }, { name: "Velocity factor" }, { name: "Coax impedance" }, { name: "Smith chart matching" }, { name: "Skin depth" }, { name: "Coax cable standards" }] },
      { title: "Power & gain", tools: [{ name: "Cascade gain, noise figure, P1dB" }, { name: "Intercept point" }, { name: "Intermodulation" }, { name: "Attenuator (Pi, T, bridged-T)" }, { name: "Power divider" }] },
      { title: "Mixing & conversion", tools: [{ name: "IF calculator" }, { name: "Image frequency" }] },
      { title: "RF components", tools: [{ name: "Common mode choke" }, { name: "Balun" }, { name: "SAW filter" }, { name: "RF diode types" }] },
      { title: "Reference", tools: [{ name: "Microwave bands & frequencies" }, { name: "Amateur radio bands" }] },
    ],
  },
  {
    id: "power",
    title: "Power electronics",
    subtitle: "Batteries, regulators, motors, supplies",
    color: "#EF9F27",
    bg: "#3B2A17",
    icon: "bolt",
    sections: [
      {
        title: "Supply & regulation",
        tools: [
          { name: "Linear regulator (LDO)" }, { name: "DC/DC buck converter" }, { name: "DC/DC boost converter" },
          { name: "Zener + transistor stabilization" }, { name: "SMPS flyback basics" },
          { name: "Inrush current limiter (NTC)" }, { name: "Constant current source/driver" }, { name: "Power factor" }, { name: "POE classes" },
        ],
      },
      { title: "Battery", tools: [{ name: "Battery runtime", was: "Runtime / capacity estimation", calc: "battery-runtime" }, { name: "Battery C-rate", was: "C-rate", calc: "c-rate" }, { name: "Battery internal resistance" }, { name: "Battery types & sizes", calc: "battery-sizes" }, { name: "Button cell sizes", was: "Button cells", calc: "button-cells" }, { name: "Accumulators" }] },
      { title: "Thermal management", tools: [{ name: "Thermal resistance (θJA / θJC)" }, { name: "Heat sink sizing" }, { name: "Power derating" }, { name: "Power density" }] },
      { title: "Motors", tools: [{ name: "Torque & power conversion" }, { name: "Back-EMF / Lenz's law" }, { name: "Stepper motor torque/step" }, { name: "RPM ↔ frequency conversion" }, { name: "Starting current estimation" }] },
      { title: "Switching & control", tools: [{ name: "Relay driver" }] },
    ],
  },
  {
    id: "pcb",
    title: "PCB & interconnect",
    subtitle: "Traces, cables, wiring",
    color: "#5BC4E0",
    bg: "#17303B",
    icon: "pcb",
    sections: [
      {
        title: "Trace current & resistance",
        tools: [
          { name: "PCB trace width / resistance" }, { name: "Trace current capacity (ampacity)" }, { name: "Trace current — IPC-2152 method" },
          { name: "Via current capacity" }, { name: "Trace inductance" },
        ],
      },
      {
        title: "Impedance",
        tools: [
          { name: "Microstrip impedance" }, { name: "Embedded microstrip impedance" }, { name: "Differential microstrip impedance" },
          { name: "Stripline impedance" }, { name: "Dual stripline impedance" }, { name: "Coplanar waveguide impedance" },
          { name: "Effective dielectric constant (Er effective)" }, { name: "Signal propagation delay" }, { name: "Crosstalk calculator" },
          { name: "Laminate material reference (Dk/Df) — IPC-4101" },
        ],
      },
      {
        title: "Vias & layout",
        tools: [
          { name: "Via impedance (R, L, C)" }, { name: "Padstack calculator" }, { name: "BGA land pattern" },
          { name: "Planar (PCB) inductor" }, { name: "Decoupling capacitor" },
        ],
      },
      { title: "Cabling", tools: [{ name: "Wire gauge (AWG/SWG)", calc: "wire-gauge" }, { name: "Cable current capacity" }, { name: "Cable resistance / voltage drop", calc: "cable-resistance-drop" }, { name: "IEC cable reference" }, { name: "Wire & cable colors", calc: "cable-colors" }] },
      { title: "Electrical safety", tools: [{ name: "Fuse/breaker sizing" }, { name: "Resettable fuse (PTC) sizing" }, { name: "TVS diode selection" }, { name: "ESD protection basics" }, { name: "Clearance & creepage distance" }, { name: "IP ratings", was: "IP-Ratings", calc: "ip-ratings" }] },
      { title: "Manufacturing & fabrication", tools: [{ name: "Copper weight converter" }, { name: "Annular ring calculator" }, { name: "Via aspect ratio calculator" }, { name: "Flex PCB bend radius" }, { name: "IPC-7351 land pattern calculator" }] },
    ],
  },
  {
    id: "tools",
    title: "Tools",
    subtitle: "Calculators, converters, generator, scope",
    color: "#9AA0A8",
    bg: "#2C2C2A",
    icon: "wrench",
    sections: [
      {
        title: "Calculators",
        tools: [
          { name: "Standard & scientific calculator", was: "Standard & Scientific Calculators", calc: "basic-calculator" },
          { name: "Ohm's law", calc: "ohms-law" },
          { name: "AC Ohm's law (impedance form)" },
          { name: "Kirchhoff's laws", calc: "kirchhoff" },
          { name: "SI prefix converter", calc: "si-prefix" },
          { name: "Scientific ↔ engineering notation", calc: "sci-eng" },
          { name: "Percent tolerance / error", calc: "percent-tolerance" },
          { name: "Generic dB ratio calculator", calc: "db-ratio" },
          { name: "dB / dBm / dBu / dBV conversion", calc: "db-absolute" },
          { name: "RMS calculator", wasSection: "Reference", calc: "rms-calculator" },
        ],
      },
      { title: "Converters", tools: [{ name: "Unit converter", calc: "unit-converter" }, { name: "PPM converter", calc: "ppm-converter" }] },
      { title: "Signal & test", tools: [{ name: "Signal generator" }, { name: "Two-tone generator" }, { name: "Oscilloscope" }, { name: "Frequency counter" }] },
      {
        title: "Reference",
        tools: [
          { name: "Formula search", was: "Formula", calc: "formula-search" }, { name: "Glossary" }, { name: "Physical constants", calc: "physical-constants" }, { name: "SI units", was: "SI-Units", calc: "si-units" },
          { name: "Quiescent current" }, { name: "4-20mA loop conversion" }, { name: "Lumen/Watt" },
        ],
      },
      { title: "Links", tools: [{ name: "Saved links" }] },
      { title: "Notes", tools: [{ name: "Personal notes" }] },
    ],
  },
];

// Home screen: the tools people reach for most, first.
const MOST_USED = ["ohms-law", "led-series-resistor", "voltage-divider", "resistor-color-code", "555-timer", "e-series"];

// Home screen shortcuts by task, for someone who knows what they want to do
// rather than which family a tool sits in.
const TASKS = [
  { id: "identify", title: "Identify a part", subtitle: "Colour bands, codes, sizes",
    calcs: ["resistor-color-code", "smd-code", "ceramic-code", "film-code", "cap-smd-code", "inductor-color-code", "inductor-smd-code", "smd-package-sizes", "cable-colors", "battery-sizes", "button-cells"] },
  { id: "resistor", title: "Choose a resistor", subtitle: "Values, power, dividers",
    calcs: ["e-series", "resistor-power-rating", "series-parallel", "voltage-divider", "current-divider", "led-series-resistor"] },
  { id: "timing", title: "Timing & clocks", subtitle: "RC, 555, crystals, UART",
    calcs: ["rc-charge", "555-timer", "multivibrator", "debounce-rc", "pwm-duty", "crystal-load", "osc-stability", "pll", "uart-baud"] },
  { id: "power", title: "Power a circuit", subtitle: "Batteries, rectifiers, wires",
    calcs: ["battery-runtime", "c-rate", "rectifier-bridge", "rectifier-halfwave-cap", "wire-gauge", "cable-resistance-drop"] },
];

// Other words people search with, English only. The tool's name, section,
// domain and former name are searched as well.
const TOOL_KEYWORDS = {
  "ohms-law": "ohm voltage current resistance power watt",
  "resistor-color-code": "colour bands resistor code iec 60062",
  "smd-code": "chip resistor marking eia-96 4r7",
  "resistor-power-rating": "wattage package 0603 0805 1206 dissipation",
  "e-series": "preferred values e12 e24 e96 standard value iec 60063",
  "series-parallel": "resistors in series parallel combine equivalent resistance",
  "voltage-divider": "potential divider resistor divider attenuator",
  "current-divider": "shunt branch current",
  "wheatstone-bridge": "bridge balance strain gauge",
  "delta-y": "star delta wye pi tee transform",
  "thermistor": "ntc ptc temperature sensor beta",
  "ceramic-code": "ceramic capacitor code marking 104 pf mlcc disc",
  "film-code": "capacitor marking 4n7 polyester polypropylene wima",
  "cap-smd-code": "tantalum capacitor marking voltage code",
  "cap-series-parallel": "capacitors in series parallel combine equivalent capacitance",
  "rc-charge": "time constant tau capacitor charge discharge",
  "cap-stored-energy": "capacitor stored energy joules charge coulomb",
  "inductor-color-code": "coil choke bands microhenry",
  "inductor-smd-code": "power inductor marking 4r7",
  "rc-filter": "low pass high pass cutoff bode",
  "rl-filter": "low pass high pass cutoff bode inductor",
  "smd-package-sizes": "footprint 0402 0603 0805 1206 imperial metric",
  "diode-biasing": "diode forward voltage vf",
  "led-series-resistor": "led resistor current limiting",
  "transistor-bias": "bjt npn bias divider operating point",
  "transistor-switch": "bjt npn pnp saturation base resistor",
  "transistor-example": "hfe beta collector current",
  "mosfet-bias": "fet gate bias",
  "mosfet-switch": "fet gate driver switching loss",
  "rectifier-halfwave": "diode rectifier ac dc",
  "rectifier-bridge": "full wave bridge rectifier diode",
  "rectifier-centertap": "full wave center tap transformer",
  "rectifier-halfwave-cap": "ripple smoothing capacitor filter",
  "thyristor-firing": "thyristor firing angle scr triac mosfet trailing edge phase dimmer",
  "opamp-inverting": "op amp gain inverting amplifier",
  "opamp-noninverting": "op amp gain non inverting amplifier",
  "opamp-buffer": "op amp buffer voltage follower unity gain",
  "opamp-comparator": "comparator schmitt trigger hysteresis threshold op amp",
  "opamp-integrator": "op amp integrator ramp",
  "opamp-differentiator": "op amp differentiator",
  "opamp-summing": "op amp adder mixer",
  "opamp-differential": "op amp difference amplifier subtractor",
  "photocell-ldr": "ldr light sensor photoresistor lux",
  "optocoupler": "opto isolator ctr",
  "spectrum-chart": "light color nm wavelength led",
  "logic-gates": "and or not nand nor xor truth table",
  "karnaugh": "k-map boolean minimise simplify logic",
  "flip-flops": "latch sr d jk t flip flop",
  "multivibrator": "astable monostable transistor oscillator",
  "555-timer": "ne555 timer astable monostable oscillator",
  "dec-hex-bin": "binary hexadecimal octal decimal base conversion",
  "ascii-table": "ascii characters code table",
  "pwm-duty": "pulse width modulation duty cycle",
  "debounce-rc": "switch bounce button rc filter",
  "i2c-pullup": "i2c pull up resistor bus capacitance",
  "uart-baud": "serial baud rate divisor error",
  "crystal-load": "crystal load capacitance pierce oscillator",
  "osc-stability": "ppm crystal drift ageing clock accuracy",
  "pll": "pll multiplier divider clock stm32 rp2040",
  "adc": "adc resolution lsb quantization bits",
  "dac": "dac resolution lsb output voltage",
  "snr": "snr enob sinad noise jitter oversampling",
  "wavelength": "frequency wavelength lambda radio",
  "battery-runtime": "battery life mah runtime capacity",
  "c-rate": "battery charge discharge rate",
  "battery-sizes": "aa aaa 18650 battery sizes",
  "button-cells": "cr2032 coin cell button battery",
  "wire-gauge": "awg swg wire size diameter",
  "cable-resistance-drop": "voltage drop wire resistance cable length",
  "cable-colors": "wire colour code mains",
  "ip-ratings": "ingress protection waterproof ip67",
  "basic-calculator": "calculator scientific",
  "kirchhoff": "kcl kvl node loop",
  "si-prefix": "prefix kilo mega micro nano pico",
  "sci-eng": "scientific engineering notation exponent",
  "percent-tolerance": "percent error tolerance",
  "db-ratio": "decibel ratio gain",
  "db-absolute": "dbm dbu dbv decibel",
  "unit-converter": "units convert inch mm temperature",
  "ppm-converter": "ppm parts per million",
  "formula-search": "formulas equations",
  "physical-constants": "constants physics",
  "si-units": "si units base derived",
  "rms-calculator": "rms peak average ac voltage",
};

// Tools that go together, shown as links at the foot of each tool. Written
// one way; the app adds the reverse link, so each pair is listed once.
const RELATED = {
  "ohms-law": ["voltage-divider", "series-parallel", "led-series-resistor", "kirchhoff", "resistor-power-rating"],
  "resistor-color-code": ["smd-code", "e-series", "resistor-power-rating", "inductor-color-code"],
  "smd-code": ["smd-package-sizes", "e-series", "cap-smd-code"],
  "resistor-power-rating": ["smd-package-sizes"],
  "e-series": ["series-parallel", "percent-tolerance"],
  "series-parallel": ["cap-series-parallel", "delta-y"],
  "voltage-divider": ["current-divider", "thermistor", "adc", "photocell-ldr", "wheatstone-bridge"],
  "current-divider": ["kirchhoff"],
  "wheatstone-bridge": ["thermistor", "delta-y"],
  "ceramic-code": ["film-code", "cap-smd-code", "e-series"],
  "cap-series-parallel": ["cap-stored-energy"],
  "rc-charge": ["debounce-rc", "555-timer", "rc-filter", "cap-stored-energy"],
  "inductor-color-code": ["inductor-smd-code"],
  "rc-filter": ["rl-filter", "opamp-integrator"],
  "diode-biasing": ["led-series-resistor", "rectifier-halfwave"],
  "led-series-resistor": ["transistor-switch", "spectrum-chart"],
  "transistor-bias": ["transistor-example", "mosfet-bias"],
  "transistor-switch": ["transistor-example", "mosfet-switch", "optocoupler"],
  "mosfet-bias": ["mosfet-switch"],
  "mosfet-switch": ["pwm-duty"],
  "rectifier-halfwave": ["rectifier-bridge", "rectifier-centertap", "rectifier-halfwave-cap"],
  "rectifier-bridge": ["rectifier-centertap", "rectifier-halfwave-cap", "rms-calculator"],
  "rectifier-halfwave-cap": ["cap-stored-energy"],
  "thyristor-firing": ["rms-calculator"],
  "opamp-inverting": ["opamp-noninverting", "opamp-summing", "opamp-differential"],
  "opamp-noninverting": ["opamp-buffer"],
  "opamp-comparator": ["555-timer"],
  "opamp-integrator": ["opamp-differentiator"],
  "photocell-ldr": ["adc", "optocoupler"],
  "spectrum-chart": ["wavelength"],
  "logic-gates": ["karnaugh", "flip-flops"],
  "multivibrator": ["555-timer"],
  "555-timer": ["pwm-duty", "flip-flops"],
  "dec-hex-bin": ["ascii-table"],
  "i2c-pullup": ["uart-baud", "rc-charge"],
  "uart-baud": ["crystal-load", "osc-stability", "pll"],
  "crystal-load": ["osc-stability", "pll"],
  "osc-stability": ["ppm-converter"],
  "adc": ["dac", "snr"],
  "dac": ["pwm-duty"],
  "snr": ["db-ratio"],
  "wavelength": ["unit-converter"],
  "battery-runtime": ["c-rate", "battery-sizes", "button-cells"],
  "battery-sizes": ["button-cells"],
  "wire-gauge": ["cable-resistance-drop", "cable-colors"],
  "cable-resistance-drop": ["ohms-law"],
  "ip-ratings": ["cable-colors"],
  "basic-calculator": ["sci-eng", "si-prefix"],
  "si-prefix": ["sci-eng", "unit-converter", "si-units"],
  "percent-tolerance": ["ppm-converter"],
  "db-ratio": ["db-absolute"],
  "formula-search": ["physical-constants", "si-units"],
  "rms-calculator": ["db-absolute"],
};
