// Generated by tools/build_manual.py. Tools with a manual section, so the
// app only offers a manual link where there is something to read.
const MANUAL_SECTIONS = new Set(["resistor-color-code", "smd-code", "resistor-power-rating", "e-series", "karnaugh", "i2c-pullup", "uart-baud", "crystal-load", "osc-stability", "pll", "adc", "dac", "snr"]);
