// Reference cases for tools/check_app.py. Each tool's cases are values
// checked by hand, against a standard or a datasheet, when it was reviewed;
// the check replays them so a later change cannot quietly break them.
//
// A case: { name, do: [steps], expect: [[selector, text]] }
//   steps:  ["set", selector, value]  types into a field or picks a <select>
//           ["click", selector]       clicks (a roller colour, a button)
//           ["pill", index]           picks a mode pill
//   expect: a field's or picker's value, or an element's text, must equal
//           the text, or match it when written as "/regex/"; "options:..."
//           compares a picker's whole list of options.
const CHECK_CASES = {
  "resistor-color-code": [
    { name: "4.7 k is yellow violet red", do: [["set", "#cc-unit", "kΩ"], ["set", "#cc-value", "4.7"]],
      expect: [['[data-value="d1"]', "4"], ['[data-value="d2"]', "7"], ['[data-value="mult"]', "×100"]] },
    { name: "0.22 Ω uses a silver multiplier", do: [["set", "#cc-unit", "Ω"], ["set", "#cc-value", "0.22"]],
      expect: [['[data-value="mult"]', "×0.01"]] },
    { name: "example: 10 k pull-up", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="ohms"]', "10 kΩ"], [".example-note", "/^10 kΩ pull-up/"]] },
    { name: "example: 4.99 k 1% is five bands", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="ohms"]', "4.99 kΩ"], ['[data-res="tol"]', "±1%"], [".pill.active", "5 bands"]] },
    { name: "example: 0.47 Ω", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="ohms"]', "470 mΩ"], ["#cc-value", "470"], ["#cc-unit", "mΩ"]] },
    { name: "bands picked by hand show in their natural unit", do: [["click", '.roller-track[data-role="mult"] [data-color="yellow"]']],
      expect: [["#cc-value", "100"], ["#cc-unit", "kΩ"]] },
    { name: "the chosen unit is remembered", do: [["set", "#cc-unit", "Ω"], ["reopen"]], expect: [["#cc-unit", "Ω"], ["#cc-value", "1000"]] },
    { name: "changing a value drops the example note", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]'], ["set", "#cc-value", "22"]],
      expect: [[".example-note", "(missing)"], [".sub", "/./"]] },
    { name: "a pill drops it too", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]'], ["pill", 2]],
      expect: [[".example-note", "(missing)"]] },
    { name: "gold band is checked against E24", do: [], expect: [['[data-res="series"]', "E24 standard value"]] },
    { name: "47 mΩ uses the pink ×0.001 band (IEC 60062:2016)", do: [["set", "#cc-unit", "mΩ"], ["set", "#cc-value", "47"]],
      expect: [['[data-value="mult"]', "×0.001"], ['[data-res="ohms"]', "47 mΩ"]] },
    { name: "example: pink band", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="4"]']],
      expect: [['[data-res="ohms"]', "47 mΩ"], ["#cc-unit", "mΩ"]] },
    { name: "grey is ±0.01% (IEC 60062:2016)", do: [["set", "#cc-unit", "kΩ"], ["set", "#cc-value", "1"], ["set", "#cc-tol", "grey"]],
      expect: [['[data-res="tol"]', "±0.01%"], ['[data-res="sub"]', "999.9 Ω – 1.0001 kΩ"]] },
  ],
  "smd-code": [
    { name: "334 is 330 k", do: [["set", "#smd-code", "334"]], expect: [['[data-res="ohms"]', "330 kΩ"]] },
    { name: "0 is a zero-ohm link", do: [["set", "#smd-code", "0"]], expect: [['[data-res="ohms"]', "0 Ω"]] },
    { name: "4992 is 49.9 k", do: [["pill", 1], ["set", "#smd-code", "4992"]], expect: [['[data-res="ohms"]', "49.9 kΩ"]] },
    { name: "10 mΩ marks 10L0 (IEC 60062:2016)", do: [["pill", 1], ["set", "#smd-unit", "Ω"], ["set", "#smd-value", "0.01"]], expect: [["#smd-code", "10L0"]] },
    { name: "47 mΩ on 3 characters is 47L, not rounded", do: [["set", "#smd-unit", "mΩ"], ["set", "#smd-value", "47"]],
      expect: [["#smd-code", "47L"], ['[data-res="err"]', ""]] },
    { name: "12.7 mΩ on 4 characters is 12L7", do: [["pill", 1], ["set", "#smd-unit", "mΩ"], ["set", "#smd-value", "12.7"]], expect: [["#smd-code", "12L7"]] },
    { name: "1 mΩ is 1L0, 0.12 mΩ L12", do: [["set", "#smd-unit", "mΩ"], ["set", "#smd-value", "1"]], expect: [["#smd-code", "1L0"]] },
    { name: "L12 reads 0.12 mΩ", do: [["set", "#smd-code", "L12"]], expect: [['[data-res="ohms"]', "0.12 mΩ"]] },
    { name: "R010 still reads 10 mΩ", do: [["pill", 1], ["set", "#smd-code", "R010"]], expect: [['[data-res="ohms"]', "10 mΩ"]] },
    { name: "10 Ω on 4 characters is 10R0", do: [["pill", 1], ["set", "#smd-unit", "Ω"], ["set", "#smd-value", "10"]], expect: [["#smd-code", "10R0"]] },
    { name: "EIA-96 01C is 10 k", do: [["pill", 2], ["set", "#smd-code", "01C"]], expect: [['[data-res="ohms"]', "10 kΩ"]] },
    { name: "3-digit is checked against E24", do: [["pill", 0], ["set", "#smd-code", "472"]], expect: [['[data-res="series"]', "E24 standard value"]] },
    { name: "4-digit is checked against E96", do: [["pill", 1], ["set", "#smd-code", "4701"]],
      expect: [['[data-res="series"]', "Not in E96 — nearest is 4.75 kΩ"]] },
    { name: "a code reads out in its natural unit", do: [["pill", 1], ["set", "#smd-code", "R010"]], expect: [["#smd-value", "10"], ["#smd-unit", "mΩ"]] },
    { name: "example: 10L0 shunt", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="ohms"]', "10 mΩ"], ["#smd-code", "10L0"], [".pill.active", "4 digit"]] },
    { name: "example: 01C", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="4"]']],
      expect: [['[data-res="ohms"]', "10 kΩ"], [".pill.active", "EIA-96"]] },
    { name: "the chosen unit is remembered", do: [["set", "#smd-unit", "Ω"], ["reopen"]], expect: [["#smd-unit", "Ω"]] },
  ],
  "resistor-power-rating": [
    { name: "1 k across 12 V is 144 mW, a 1206 or 1210 at half", do: [],
      expect: [['[data-res="p"]', "144 mW"], ['[data-res="sub"]', "12 mA through it"], ['[data-res="min"]', "1206"], ['[data-res="half"]', "1210"], ['[data-res="tht"]', "1/2 W"]] },
    { name: "example: 0.1 Ω shunt at 2 A", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="p"]', "400 mW"], ['[data-res="sub"]', "200 mV across it"], ['[data-res="min"]', "1210"], ['[data-res="half"]', "2512"], ['[data-res="tht"]', "1 W"]] },
    { name: "example: 1 MΩ at 100 V is sized by voltage", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="p"]', "10 mW"], ['[data-res="min"]', "0805"], ['[data-res="half"]', "0805"]] },
    { name: "above every chip's voltage", do: [["set", "#rpr-r-unit", "MΩ"], ["set", "#rpr-r", "1"], ["set", "#rpr-x", "300"]],
      expect: [['[data-res="min"]', "Over 200 V"], ['[data-res="err"]', "/series to share it/"]] },
    { name: "the filter and mode are remembered", do: [["click", '.filter-btn[data-filter="smd"]'], ["pill", 1], ["reopen"]],
      expect: [[".filter-btn.active", "SMD"], [".pill.active", "Current through"]] },
  ],
  "e-series": [
    { name: "9.2 k is E192 (IEC 60063's 920)", do: [["pill", 5], ["set", "#es-unit", "kΩ"], ["set", "#es-value", "9.2"]],
      expect: [['[data-res="drift"]', "E192 standard value, exactly"]] },
    { name: "97 k rounds up, highlighted", do: [["pill", 2], ["set", "#es-unit", "kΩ"], ["set", "#es-value", "97"]],
      expect: [['[data-res="ohms"]', "100 kΩ"], [".eseries-cell.hit", "100 kΩ"]] },
    { name: "example: 26.36 k in E96 is 26.1 k", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="ohms"]', "26.1 kΩ"], ['[data-res="drift"]', "-0.99% from 26.36 kΩ"], [".pill.active", "E96"]] },
    { name: "example: 158 Ω in E24 is 160 Ω, in its own unit", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="ohms"]', "160 Ω"], ['[data-res="drift"]', "+1.27% from 158 Ω"], ["#es-value", "158"], ["#es-unit", "Ω"]] },
    { name: "example: 4.7 k in E96 is 4.75 k", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="ohms"]', "4.75 kΩ"], ['[data-res="drift"]', "+1.06% from 4.7 kΩ"]] },
    { name: "the series and unit are remembered", do: [["pill", 4], ["set", "#es-unit", "Ω"], ["reopen"]],
      expect: [[".pill.active", "E96"], ["#es-unit", "Ω"]] },
  ],
  "series-parallel": [
    { name: "1 k + 1 k", do: [], expect: [['[data-res="total"]', "2 kΩ"]] },
    { name: "1 k ∥ 1 k", do: [["pill", 1]], expect: [['[data-res="total"]', "500 Ω"]] },
    { name: "example: 10 k ∥ 10 k is 5 k", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="total"]', "5 kΩ"], [".pill.active", "Parallel"], ["#sp-tol", "5"]] },
    { name: "example: 1 k + 2.2 k, nearest single 3.3 k", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="total"]', "3.2 kΩ"], ['[data-res="detail"]', "/nearest single E24 3.3 kΩ/"]] },
    { name: "example: four 470 Ω in parallel", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="total"]', "117.5 Ω"]] },
    { name: "example: 1 k ∥ 1 M", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="total"]', "999 Ω"]] },
    { name: "the mode and tolerance are remembered", do: [["pill", 1], ["set", "#sp-tol", "5"], ["reopen"]],
      expect: [[".pill.active", "Parallel"], ["#sp-tol", "5"]] },
  ],
  "voltage-divider": [
    { name: "12 V, 10 k / 10 k", do: [], expect: [['[data-res="solved"]', "6 V"]] },
    { name: "shorthand 4k7 in a kΩ field is 4.7", do: [["set", 'input[data-var="r2"]', "4k7"]],
      expect: [['input[data-var="r2"]', "4.7"], ['[data-res="solved"]', "3.837 V"]] },
    { name: "a decimal comma is read", do: [["set", 'input[data-var="r2"]', "4,7"]], expect: [['[data-res="solved"]', "3.837 V"]] },
    { name: "shorthand in an Ω field", do: [["set", 'select[data-unit="r2"]', "Ω"], ["set", 'input[data-var="r2"]', "4k7"]],
      expect: [['input[data-var="r2"]', "4700"], ['[data-res="solved"]', "3.837 V"]] },
    { name: "a chosen unit is remembered", do: [["set", 'select[data-unit="r2"]', "Ω"], ["reopen"]],
      expect: [['select[data-unit="r2"]', "Ω"]] },
    { name: "12 V, 10 k / 4.7 k", do: [["set", 'input[data-var="r2"]', "4.7"]], expect: [['[data-res="solved"]', "3.837 V"]] },
    { name: "example: 5 V to 3.3 V, R2", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="solved"]', "19.41 kΩ"], ['[data-res="detail"]', "/E96 → 19.6 kΩ, Vout 3.31 V/"], [".pill.active", "R2"]] },
    { name: "example: 12 V to 3.3 V, R1", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="solved"]', "26.36 kΩ"], ['[data-res="detail"]', "/E96 → 26.1 kΩ, Vout 3.32 V/"]] },
    { name: "example: battery into an ADC", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="solved"]', "3.141 V"], ['[data-res="detail"]', "/94.6 µA/"], ['[data-hint="r2"]', "E96"]] },
    { name: "the solve and tolerance are remembered", do: [["pill", 1], ["set", "#vd-tol", "5"], ["reopen"]],
      expect: [[".pill.active", "R1"], ["#vd-tol", "5"]] },
  ],
  "current-divider": [
    { name: "20 mA into 1 k ∥ 2 k", do: [["set", 'input[data-var="r2"]', "2"]], expect: [['[data-res="solved"]', "13.33 mA"]] },
    { name: "example: 1 k and 2 k share 20 mA", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="solved"]', "13.33 mA"], ['[data-res="detail"]', "/I2 6.67 mA/"]] },
    { name: "example: meter shunt is 1.01 Ω", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="solved"]', "1.01 Ω"], ['[data-res="detail"]', "/E96 → 1.02 Ω, I1 1.01 mA/"], [".pill.active", "R2"]] },
    { name: "example: R1 for 15 of 20 mA", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="solved"]', "333.3 Ω"], ['[data-res="detail"]', "/E96 → 332 Ω/"]] },
    { name: "the solve, tolerance and units are remembered", do: [["pill", 1], ["set", "#cd-tol", "5"], ["set", 'select[data-unit="iin"]', "A"], ["reopen"]],
      expect: [[".pill.active", "R1"], ["#cd-tol", "5"], ['select[data-unit="iin"]', "A"]] },
  ],
  "wheatstone-bridge": [
    { name: "1 k, 2 k, 3 k balance with 6 k", do: [["set", 'input[data-var="r2"]', "2"], ["set", 'input[data-var="r3"]', "3"]],
      expect: [['[data-res="solved"]', "6 kΩ"]] },
    { name: "example: ×10 ratio reads 4.75 k", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="solved"]', "4.75 kΩ"], ['[data-res="detail"]', "/Ratio R2 \/ R1 = 10/"]] },
    { name: "example: PT100 at 25 °C", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="solved"]', "109.7 Ω"], [".pill.active", "R3"]] },
    { name: "example: ×100 ratio arm", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="solved"]', "100 kΩ"], ['[data-res="detail"]', "E96 standard value"]] },
    { name: "the solve, tolerance and units are remembered", do: [["pill", 3], ["set", "#wb-tol", "5"], ["set", 'select[data-unit="r1"]', "Ω"], ["reopen"]],
      expect: [[".pill.active", "R3"], ["#wb-tol", "5"], ['select[data-unit="r1"]', "Ω"]] },
  ],
  "delta-y": [
    { name: "10, 20, 30 Ω delta", do: [["set", 'input[data-var="ab"]', "10"], ["set", 'input[data-var="bc"]', "20"], ["set", 'input[data-var="ca"]', "30"]],
      expect: [['[data-res="a"]', "5 Ω"], ['[data-res="b"]', "3.333 Ω"], ['[data-res="c"]', "10 Ω"]] },
    { name: "example: equal 300 Ω is 100 Ω a leg", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="a"]', "100 Ω"], ['[data-res="b"]', "100 Ω"], ['[data-res="c"]', "100 Ω"]] },
    { name: "example: 6 dB T pad to π", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="ab"]', "150.5 Ω"], ['[data-res="bc"]', "150.5 Ω"], ['[data-res="ca"]', "37.34 Ω"], [".pill.active", "Y → Δ"]] },
    { name: "the direction and units are remembered", do: [["pill", 1], ["set", 'select[data-unit="a"]', "kΩ"], ["reopen"]],
      expect: [[".pill.active", "Y → Δ"], ['select[data-unit="a"]', "kΩ"]] },
  ],
  "thermistor": [
    { name: "Vishay 10 k, B 3977, at 85 °C", do: [["set", "#th-coef", "3977"], ["set", "#th-temp", "85"]], expect: [["#th-res", "1.07"]] },
    { name: "a typographic minus is read", do: [["set", "#th-coef", "3977"], ["set", "#th-temp", "−20"]], expect: [["#th-res", "107.1"]] },
    { name: "the ± key makes it negative", do: [["set", "#th-coef", "3977"], ["set", "#th-temp", "20"], ["click", "#th-temp + .sign-btn"]],
      expect: [["#th-temp", "-20"], ["#th-res", "107.1"]] },
    { name: "the result is the resistance at the temperature typed", do: [["set", "#th-coef", "3977"], ["set", "#th-temp", "85"]],
      expect: [['[data-res="label"]', "Resistance at 85 °C"], ['[data-res="main"]', "1.07 kΩ"]] },
    { name: "and the temperature at the resistance typed", do: [["set", "#th-coef", "3977"], ["set", "#th-res", "33.9"]],
      expect: [['[data-res="label"]', "Temperature at 33.9 kΩ"], ['[data-res="main"]', "0 °C"], ["#th-temp", "0"]] },
    { name: "example: NTC at 37 °C", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="main"]', "5.968 kΩ"], ["#th-coef", "3977"]] },
    { name: "example: Pt100 at 100 °C", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="main"]', "138.5 Ω"], [".pill.active", "PTC (linear α)"], ['[data-res="sens"]', "/0.385 %\/°C/"]] },
    { name: "the model and units are remembered", do: [["pill", 1], ["set", "#th-res-unit", "Ω"], ["reopen"]],
      expect: [[".pill.active", "PTC (linear α)"], ["#th-res-unit", "Ω"]] },
  ],
  "ceramic-code": [
    { name: "104 is 100 nF", do: [["set", "#cer-code", "104"]], expect: [['[data-res="value"]', "100 nF"]] },
    { name: "479 is 4.7 pF (EIA-198 ×0.1)", do: [["set", "#cer-code", "479"]], expect: [['[data-res="value"]', "4.7 pF"]] },
    { name: "101D is ±0.5% above 10 pF", do: [["set", "#cer-code", "101D"]], expect: [['[data-res="tol"]', "±0.5%"]] },
    { name: "no letter is checked against E6", do: [["set", "#cer-code", "182"]], expect: [['[data-res="series"]', "Not in E6 — nearest is 1.5 nF"]] },
    { name: "K is checked against E12", do: [["set", "#cer-code", "182K"]], expect: [['[data-res="series"]', "E12 standard value"]] },
    { name: "a pF tolerance implies no series", do: [["set", "#cer-code", "479C"]], expect: [['[data-res="series"]', "Tolerance in pF: no E-series implied"]] },
    { name: "at 10 pF the letters are percentages", do: [["set", "#cer-code", "100C"]], expect: [['[data-res="tol"]', "±0.25%"]] },
    { name: "below 10 pF they are picofarads", do: [["set", "#cer-code", "8p2C"]], expect: [['[data-res="value"]', "8.2 pF"], ['[data-res="tol"]', "±0.25 pF"]] },
    { name: "4.7 pF is written 4p7", do: [["set", "#cer-unit", "pF"], ["set", "#cer-value", "4.7"]], expect: [["#cer-code", "4p7"]] },
    { name: "4R7 is read too", do: [["set", "#cer-code", "4R7"]], expect: [['[data-res="value"]', "4.7 pF"]] },
    { name: "T is −10/+50% (IEC 60062, table 7)", do: [["set", "#cer-code", "104T"]], expect: [['[data-res="tol"]', "−10% / +50%"]] },
    { name: "a code reads out in its natural unit", do: [["set", "#cer-code", "479"]], expect: [["#cer-value", "4.7"], ["#cer-unit", "pF"]] },
    { name: "example: 220J", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="value"]', "22 pF"], ['[data-res="tol"]', "±5%"], ['[data-res="series"]', "E24 standard value"], ["#cer-code", "220J"]] },
    { name: "example: 479 stays 479", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="value"]', "4.7 pF"], ["#cer-code", "479"]] },
    { name: "the mode and unit are remembered", do: [["pill", 1], ["set", "#cer-unit", "pF"], ["reopen"]],
      expect: [[".pill.active", "4 digit"], ["#cer-unit", "pF"]] },
  ],
  "film-code": [
    { name: "102H is ±3% (IEC 60062, table 6)", do: [["set", "#film-code", "102H"]], expect: [['[data-res="value"]', "1 nF"], ['[data-res="tol"]', "±3%"]] },
    { name: "4N7J reads case-blind", do: [["pill", 1], ["set", "#film-code", "4N7J"]], expect: [['[data-res="value"]', "4.7 nF"], ['[data-res="tol"]', "±5%"]] },
    { name: "no letter is checked against E12", do: [["set", "#film-code", "562"]], expect: [['[data-res="series"]', "E12 standard value"]] },
    { name: "J is checked against E24", do: [["set", "#film-code", "912J"]], expect: [['[data-res="series"]', "E24 standard value"]] },
    { name: "M is checked against E6", do: [["set", "#film-code", "562M"]], expect: [['[data-res="series"]', "Not in E6 — nearest is 4.7 nF"]] },
    { name: "example: n33K is 330 pF", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="value"]', "330 pF"], ["#film-code", "n33K"], ["#film-value", "330"], ["#film-unit", "pF"], [".pill.active", "Direct (p/n/µ)"]] },
    { name: "example: 104J", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="value"]', "100 nF"], ['[data-res="series"]', "E24 standard value"]] },
    { name: "the mode and unit are remembered", do: [["pill", 1], ["set", "#film-unit", "µF"], ["reopen"]],
      expect: [[".pill.active", "Direct (p/n/µ)"], ["#film-unit", "µF"]] },
  ],
  "cap-smd-code": [
    { name: "227A (AVX TAJ)", do: [["set", "#csmd-code", "227A"]], expect: [['[data-res="value"]', "220 µF"], ['[data-res="letter"]', "Rated 10 V"]] },
    { name: "J106, letter first", do: [["set", "#csmd-code", "J106"]], expect: [['[data-res="value"]', "10 µF"], ['[data-res="letter"]', "Rated 6.3 V"]] },
    { name: "a voltage letter is checked against E6", do: [["set", "#csmd-code", "156A"]], expect: [['[data-res="series"]', "E6 standard value"]] },
    { name: "a tolerance letter picks the series", do: [["pill", 1], ["set", "#csmd-code", "825K"]], expect: [['[data-res="series"]', "E12 standard value"]] },
    { name: "a code reads out in its natural unit", do: [["set", "#csmd-code", "471"]], expect: [["#csmd-value", "470"], ["#csmd-unit", "pF"]] },
    { name: "example: 475K", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="value"]', "4.7 µF"], ['[data-res="letter"]', "±10%"], [".pill.active", "Tolerance letter"], ["#csmd-code", "475K"]] },
    { name: "the mode and unit are remembered", do: [["pill", 1], ["set", "#csmd-unit", "nF"], ["reopen"]],
      expect: [[".pill.active", "Tolerance letter"], ["#csmd-unit", "nF"]] },
  ],
  "cap-series-parallel": [
    { name: "100 n ∥ 100 n", do: [], expect: [['[data-res="total"]', "200 nF"]] },
    { name: "100 n in series with 100 n", do: [["pill", 1]], expect: [['[data-res="total"]', "50 nF"]] },
    { name: "example: 100 n ∥ 10 µ", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="total"]', "10.1 µF"]] },
    { name: "example: crystal load caps in series", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="total"]', "11 pF"], ['[data-res="detail"]', "/one E24 part would do it/"], [".pill.active", "Series"]] },
    { name: "example: 100 n ∥ 47 n", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="total"]', "147 nF"], ['[data-res="detail"]', "/nearest single E12 150 nF/"]] },
    { name: "example: supercaps", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="total"]', "5 F"]] },
    { name: "the mode and tolerance are remembered", do: [["pill", 1], ["set", "#sp-tol", "5"], ["reopen"]],
      expect: [[".pill.active", "Series"], ["#sp-tol", "5"]] },
  ],
  "rc-charge": [
    { name: "1 τ reaches 63.21%", do: [], expect: [['[data-res="label"]', "Voltage after 1 s"], ['[data-res="main"]', "3.161 V"], ['[data-res="pct"]', "63.21%"]] },
    { name: "4.5 V of 5 V takes ln 10 τ", do: [["set", "#rc-volt", "4.5"]],
      expect: [["#rc-time", "2.303"], ['[data-res="label"]', "Time to reach 4.5 V"], ['[data-res="main"]', "2.303 s"]] },
    { name: "example: power-on reset", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="main"]', "93.16 ms"], ["#rc-time", "93.16"], ["#rc-time-unit", "ms"]] },
    { name: "example: debounce after 5 τ", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="main"]', "4.966 V"], ['[data-res="pct"]', "99.33%"], ['[data-res="tau"]', "1 ms"]] },
    { name: "example: bleeder to 50 V", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="main"]', "97.73 s"], ['[data-res="label"]', "Time to fall to 50 V"], [".pill.active", "Discharging"]] },
    { name: "the mode and units are remembered", do: [["pill", 1], ["set", "#rc-c-unit", "nF"], ["set", "#rc-time-unit", "ms"], ["reopen"]],
      expect: [[".pill.active", "Discharging"], ["#rc-c-unit", "nF"], ["#rc-time-unit", "ms"]] },
    { name: "100u in a µF field", do: [["set", "#rc-c", "100u"]], expect: [["#rc-c", "100"], ['[data-res="tau"]', "1 s"]] },
    { name: "1m in a µF field is 1000", do: [["set", "#rc-c", "1m"]], expect: [["#rc-c", "1000"], ['[data-res="tau"]', "10 s"]] },
  ],
  "cap-stored-energy": [
    { name: "1000 µF at 12 V", do: [], expect: [['[data-res="solved"]', "72 mJ"], ['[data-res="charge"]', "12 mC"]] },
    { name: "example: camera flash", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="solved"]', "17.97 J"], ['[data-res="charge"]', "108.9 mC"]] },
    { name: "example: mains bulk capacitor", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="solved"]', "24.82 J"]] },
    { name: "example: C for 1 J at 12 V", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="solved"]', "13.89 mF"], [".pill.active", "Capacitance"]] },
    { name: "the solve and units are remembered", do: [["pill", 1], ["set", 'select[data-unit="e"]', "J"], ["reopen"]],
      expect: [[".pill.active", "Voltage"], ['select[data-unit="e"]', "J"]] },
  ],
  "rc-filter": [
    { name: "10 k and 100 n: fc 159.2 Hz", do: [], expect: [['[data-res="solved"]', "159.2 Hz"]] },
    { name: "at fc: −3.01 dB, 45° lag", do: [], expect: [['[data-res="db"]', "/^-3\\.01\\d* dB$/"], ['[data-res="phase"]', "/^-45° phase shift/"]] },
    { name: "2 buffered poles: system −3 dB at 0.644 fc", do: [["set", "#rcf-poles", "2"]], expect: [['[data-res="syscutoff"]', "/102\\.4 Hz/"]] },
    { name: "example: PWM filter, −36 dB at 1 kHz", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="solved"]', "15.92 Hz"], ['[data-res="db"]', "/^-35\\.9\\d* dB$/"]] },
    { name: "example: coupling high-pass, 20 Hz 2.1 dB down", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="db"]', "/^-2\\.1\\d* dB$/"], ['#rcf-topology .pill.active', "High-pass"]] },
    { name: "example: anti-alias C", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="solved"]', "7.958 nF"], ['[data-res="db"]', "/^-3\\.4\\d* dB$/"]] },
    { name: "only real units", do: [], expect: [['select[data-unit="c"]', "options:pFnFµF"], ['select[data-unit="r"]', "options:ΩkΩMΩ"]] },
    { name: "topology, solve, poles and units are remembered", do: [["click", '.pill[data-topo="highpass"]'], ["click", '.pill[data-pill="c"]'], ["set", "#rcf-poles", "3"], ["set", 'select[data-unit="r"]', "Ω"], ["reopen"]],
      expect: [['#rcf-topology .pill.active', "High-pass"], ['.pill[data-pill].active', "C"], ["#rcf-poles", "3"], ['select[data-unit="r"]', "Ω"]] },
  ],
  "led-series-resistor": [
    { name: "red on 5 V at 10 mA: 310 Ω, next E24 up 330 Ω", do: [],
      expect: [['[data-res="r"]', "310 Ω"], ['[data-res="e24"]', "/330 Ω → 9\\.39 mA/"]] },
    { name: "a standard value exactly is said so", do: [["set", "#led-vs", "5"], ["set", "#led-vf", "2"], ["set", "#led-i", "20"]],
      expect: [['[data-res="r"]', "150 Ω"], ['[data-res="e24"]', "150 Ω is an E24 standard value."]] },
    { name: "rounds up, never down: 345 Ω → 360 Ω", do: [["set", "#led-vs", "5"], ["set", "#led-vf", "1.55"], ["set", "#led-i", "10"]],
      expect: [['[data-res="r"]', "345 Ω"], ['[data-res="e24"]', "/360 Ω/"]] },
    { name: "supply below Vf is refused", do: [["set", "#led-vs", "3"], ["set", "#led-vf", "3.3"]], expect: [['[data-res="err"]', "/must be above/"]] },
    { name: "the bright green preset is 3.3 V (Kingbright WP7113ZGC)", do: [["set", "#led-vf-preset", "Green, bright (3.3 V)"]], expect: [["#led-vf", "3.3"]] },
    { name: "example: three red LEDs on 12 V", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="r"]', "315 Ω"], ['[data-res="e24"]', "/330 Ω/"]] },
    { name: "the series and current unit are remembered", do: [["set", "#led-series", "E96"], ["set", "#led-i-unit", "A"], ["reopen"]],
      expect: [["#led-series", "E96"], ["#led-i-unit", "A"]] },
  ],
  "opamp-inverting": [
    { name: "10 k / 100 k, 0.5 V: gain −10, −5 V", do: [],
      expect: [['[data-res="vout"]', "-5 V"], ['[data-res="gain"]', "-10×"], ['[data-res="db"]', "20 dB"], ['[data-res="iin"]', "50 µA"], ['[data-res="bw"]', "90.91 kHz"]] },
    { name: "example: unity inverter, bandwidth GBW / 2", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="vout"]', "-1 V"], ['[data-res="bw"]', "500 kHz"], ['[data-res="db"]', "0 dB"]] },
    { name: "example: mic preamp, 20.83 kHz", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="vout"]', "-940 mV"], ['[data-res="bw"]', "20.83 kHz"]] },
    { name: "example: clipping 1.5 V short of the rail", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="vout"]', "-10.5 V"], ['[data-res="clip"]', "/-20 V.*-10\.5 V/"]] },
    { name: "rail-to-rail (headroom 0) clips at the rail", do: [["set", "#oa-vin", "2"], ["set", "#oa-headroom", "0"]],
      expect: [['[data-res="vout"]', "-12 V"]] },
    { name: "units and op-amp are remembered", do: [["set", "#oa-vin-unit", "mV"], ["set", "#oa-gbw", "5.25"], ["set", "#oa-rf-unit", "MΩ"], ["reopen"]],
      expect: [["#oa-vin-unit", "mV"], ["#oa-gbw", "5.25"], ["#oa-rf-unit", "MΩ"]] },
  ],
  "opamp-noninverting": [
    { name: "10 k / 100 k, 0.5 V: gain 11, 5.5 V", do: [],
      expect: [['[data-res="vout"]', "5.5 V"], ['[data-res="gain"]', "11×"], ['[data-res="db"]', "20.83 dB"], ['[data-res="ifb"]', "50 µA"], ['[data-res="bw"]', "90.91 kHz"]] },
    { name: "example: Rf = R1 doubles, GBW / 2", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="vout"]', "2 V"], ['[data-res="db"]', "6.02 dB"], ['[data-res="bw"]', "500 kHz"]] },
    { name: "example: gain 101, 9.901 kHz", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="vout"]', "2.02 V"], ['[data-res="bw"]', "9.901 kHz"]] },
    { name: "example: clipping at 10.5 V", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="vout"]', "10.5 V"], ['[data-res="clip"]', "/16\.5 V.*10\.5 V/"]] },
    { name: "Rf 0: a buffer, gain 1, all the GBW", do: [["set", "#on-rf", "0"]],
      expect: [['[data-res="gain"]', "1×"], ['[data-res="bw"]', "1 MHz"]] },
    { name: "units and op-amp are remembered", do: [["set", "#on-vin-unit", "mV"], ["set", "#on-headroom", "0.1"], ["set", "#on-gbw-unit", "kHz"], ["reopen"]],
      expect: [["#on-vin-unit", "mV"], ["#on-headroom", "0.1"], ["#on-gbw-unit", "kHz"]] },
  ],
  "opamp-buffer": [
    { name: "100 kΩ source, 10 kΩ load, 1 V: buffered 1 V, 90.9 mV without", do: [],
      expect: [['[data-res="vout"]', "1 V"], ['[data-res="direct"]', "90.91 mV"], ['[data-res="loss"]', "90.9%"], ['[data-res="iload"]', "100 µA"], ['[data-res="bw"]', "1 MHz"]] },
    { name: "example: buffering a divider", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="vout"]', "2.5 V"], ['[data-res="direct"]', "416.7 mV"], ['[data-res="iload"]', "2.5 mA"]] },
    { name: "example: 50 Ω source loses 0.5%", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="loss"]', "0.498%"]] },
    { name: "example: 11 V clips at 10.5 V", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="vout"]', "10.5 V"], ['[data-res="clip"]', "/11 V.*10\.5 V/"]] },
    { name: "a 100 Ω load at 5 V warns about output current", do: [["set", "#ob-vin", "5"], ["set", "#ob-rl-unit", "Ω"], ["set", "#ob-rl", "100"]],
      expect: [['[data-res="iload"]', "50 mA"], ['[data-res="iwarn"]', "/50 mA/"]] },
    { name: "units and op-amp are remembered", do: [["set", "#ob-rs-unit", "Ω"], ["set", "#ob-gbw", "5.25"], ["reopen"]],
      expect: [["#ob-rs-unit", "Ω"], ["#ob-gbw", "5.25"]] },
  ],
  "opamp-comparator": [
    { name: "comparator 10 k / 10 k on ±12 V: switches at 6 V, 7 V in → low", do: [],
      expect: [['[data-res="vref"]', "6 V"], ['[data-res="state"]', "LOW, -10.5 V"], ['[data-res="margin"]', "+1 V"], ['[data-res="idiv"]', "600 µA"]] },
    { name: "example: Schmitt 100 k gives 1 V of hysteresis", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="vth"]', "6.214 V"], ['[data-res="vtl"]', "5.214 V"], ['[data-res="hyst"]', "1 V"], ['[data-res="state"]', "keeps its last state"]] },
    { name: "example: Rf 22 k, 3.889 V band", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="vth"]', "6.833 V"], ['[data-res="vtl"]', "2.944 V"], ['[data-res="hyst"]', "3.889 V"]] },
    { name: "example: zero-crossing ±1.05 V, 2 V in → high", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="vth"]', "1.05 V"], ['[data-res="vtl"]', "-1.05 V"], ['[data-res="state"]', "HIGH, +10.5 V"]] },
    { name: "rail-to-rail: Schmitt points move with the output level", do: [["pill", 1], ["set", "#oc-headroom", "0"]],
      expect: [['[data-res="vth"]', "6.286 V"], ['[data-res="vtl"]', "5.143 V"]] },
    { name: "mode and units are remembered", do: [["pill", 2], ["set", "#oc-rin-unit", "MΩ"], ["set", "#oc-vin-unit", "mV"], ["reopen"]],
      expect: [[".pill.active", "Schmitt non-inv"], ["#oc-rin-unit", "MΩ"], ["#oc-vin-unit", "mV"]] },
  ],
  "opamp-integrator": [
    { name: "square, 10 k / 100 nF, 1 V, 100 Hz: 5 V p-p triangle", do: [],
      expect: [['[data-res="vout"]', "2.5 V"], ['[data-res="vpp"]', "5 V"], ['[data-res="ramp"]', "1 V/ms"], ['[data-res="tau"]', "1 ms"], ['[data-res="f0"]', "159.2 Hz"], ['[data-res="half"]', "5 ms"]] },
    { name: "example: 1 kHz square, 10 V/ms", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="vpp"]', "5 V"], ['[data-res="ramp"]', "10 V/ms"], ['[data-res="tau"]', "100 µs"]] },
    { name: "example: sine at 100 Hz, gain 1.592", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="vout"]', "1.592 V"], ['[data-res="gain"]', "1.592×"], ['[data-res="db"]', "4.04 dB"]] },
    { name: "example: 10 Hz clips at 10.5 V", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="vout"]', "10.5 V"], ['[data-res="clip"]', "/25 V.*10\\.5 V/"]] },
    { name: "wave and units are remembered", do: [["pill", 1], ["set", "#oi-c-unit", "µF"], ["set", "#oi-freq-unit", "kHz"], ["reopen"]],
      expect: [[".pill.active", "Sine in"], ["#oi-c-unit", "µF"], ["#oi-freq-unit", "kHz"]] },
    { name: "example: Rf 1 MΩ, fL 1.592 Hz, 100 Hz barely changed", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="vout"]', "2.499 V"], ['[data-res="fl"]', "1.592 Hz"], ['[data-res="ramp"]', "1 V/ms"]] },
    { name: "Rf 1 MΩ, sine at 100 Hz: gain 1.591, leads 90.9°", do: [["pill", 1], ["set", "#oi-rf", "1"]],
      expect: [['[data-res="gain"]', "1.591×"], ['[data-res="lead"]', "90.9°"]] },
    { name: "Rf 1 MΩ at 10 Hz: below 10 × fL, warned", do: [["set", "#oi-rf", "1"], ["set", "#oi-freq", "10"]],
      expect: [['[data-res="lowf"]', "/15\\.92 Hz/"]] },
  ],
  "opamp-differentiator": [
    { name: "triangle, 10 k / 100 nF, 1 V, 100 Hz: ±0.4 V square", do: [],
      expect: [['[data-res="vout"]', "400 mV"], ['[data-res="vpp"]', "800 mV"], ['[data-res="slope"]', "400 V/s"], ['[data-res="tau"]', "1 ms"], ['[data-res="half"]', "5 ms"]] },
    { name: "example: 1 kHz triangle, 4 V/ms", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="vout"]', "400 mV"], ['[data-res="slope"]', "4 V/ms"], ['[data-res="tau"]', "100 µs"]] },
    { name: "example: sine at 1 kHz, gain 6.283, lags 90°", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="vout"]', "6.283 V"], ['[data-res="gain"]', "6.283×"], ['[data-res="lag"]', "90°"], ['[data-res="db"]', "15.96 dB"]] },
    { name: "example: 10 kHz clips at 10.5 V", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="vout"]', "10.5 V"], ['[data-res="clip"]', "/62.83 V.*10.5 V/"]] },
    { name: "example: Rs 100 Ω, fH 15.92 kHz, gain 6.271", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="fh"]', "15.92 kHz"], ['[data-res="gain"]', "6.271×"], ['[data-res="lag"]', "93.6°"]] },
    { name: "Rs 1 kΩ at 1 kHz: above fH / 10, warned", do: [["pill", 1], ["set", "#od-freq-unit", "kHz"], ["set", "#od-freq", "1"], ["set", "#od-rs-unit", "kΩ"], ["set", "#od-rs", "1"]],
      expect: [['[data-res="highf"]', "/159.2 Hz.*= 10/"]] },
    { name: "wave and units are remembered", do: [["pill", 1], ["set", "#od-c-unit", "µF"], ["set", "#od-rs-unit", "kΩ"], ["reopen"]],
      expect: [[".pill.active", "Sine in"], ["#od-c-unit", "µF"], ["#od-rs-unit", "kΩ"]] },
  ],
  "thyristor-firing": [
    { name: "TRIAC, 120 V, 144 Ω, α 90°: half power, 50 W", do: [],
      expect: [['[data-res="p"]', "50 W"], ['[data-res="pct"]', "50%"], ['[data-res="vrms"]', "84.85 V"], ['[data-res="delay"]', "4.167 ms"], ['[data-res="piv"]', "169.7 V"]] },
    { name: "SCR, 120 V, α 90°: Vdc = Vp / 2π", do: [["pill", 0]],
      expect: [['[data-res="vdc"]', "27.01 V"], ['[data-res="vrms"]', "60 V"], ['[data-res="p"]', "25 W"]] },
    { name: "α 0°: full power", do: [["set", "#tf-alpha-input", "0"]], expect: [['[data-res="pct"]', "100%"], ['[data-res="p"]', "100 W"]] },
    { name: "example: 1 kW heater at 60°", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="p"]', "/^80[45]\\.\\d W$/"], ['[data-res="delay"]', "3.333 ms"]] },
    { name: "example: SCR at 45°", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="vdc"]', "9.222 V"]] },
    { name: "MOSFET, β 90°, Rds 0: half power, 50 W", do: [["pill", 2], ["set", "#tf-rds", "0"]],
      expect: [['[data-res="p"]', "50 W"], ['[data-res="pct"]', "50%"], ['[data-res="loss"]', "0 W"]] },
    { name: "MOSFET, 2 × 100 mΩ: 49.86 W to the load, 69.2 mW lost", do: [["pill", 2]],
      expect: [['[data-res="p"]', "49.86 W"], ['[data-res="loss"]', "69.25 mW"]] },
    { name: "MOSFET β 120° = TRIAC α 60°", do: [["pill", 2], ["set", "#tf-rds", "0"], ["set", "#tf-alpha-input", "120"]],
      expect: [['[data-res="pct"]', "80.4%"]] },
    { name: "example: trailing-edge dimmer", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="delay"]', "6.667 ms"], [".pill.active", "MOSFET"]] },
    { name: "device, mains and unit are remembered", do: [["pill", 0], ["set", "#tf-freq", "50"], ["set", "#tf-rload-unit", "kΩ"], ["reopen"]],
      expect: [[".pill.active", "SCR"], ["#tf-freq", "50"], ["#tf-rload-unit", "kΩ"]] },
  ],
  "rectifier-halfwave-cap": [
    { name: "bridge, 12 V AC, 220 Ω, 1000 µF, 60 Hz", do: [],
      expect: [['[data-res="vdc"]', "15.31 V"], ['[data-res="vrpp"]', "532.4 mV"], ['[data-res="rule"]', "589.8 mV"], ['[data-res="piv"]', "16.97 V"]] },
    { name: "example: 1 A from 2200 µF — simulated 3.4 V, rule 4.9 V", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="vdc"]', "13.95 V"], ['[data-res="vrpp"]', "3.401 V"], ['[data-res="rule"]', "4.915 V"]] },
    { name: "example: half-wave doubles the ripple, PIV 2Vp − Vf", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="vrpp"]', "6.732 V"], ['[data-res="piv"]', "33.24 V"], [".pill.active", "Half-wave"]] },
    { name: "example: 50 Hz, 4700 µF", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="vrpp"]', "2.132 V"]] },
    { name: "mode, frequency and units are remembered", do: [["pill", 0], ["set", "#rhc-freq", "50"], ["set", "#rhc-cap-unit", "nF"], ["reopen"]],
      expect: [[".pill.active", "Half-wave"], ["#rhc-freq", "50"], ["#rhc-cap-unit", "nF"]] },
  ],
  "rectifier-centertap": [
    { name: "12 V a half, 0.7 V, 100 Ω: Vdc 10.11 V exact, PIV 2Vp − Vf", do: [],
      expect: [['[data-res="vdc"]', "10.11 V"], ['[data-res="idc"]', "101.1 mA"], ['[data-res="piv"]', "33.24 V"], ['[data-res="ripple"]', "0.515"], ['[data-res="eff"]', "79.1%"]] },
    { name: "ideal diodes: 2Vp/π, ripple 0.483", do: [["set", "#rc-vf", "0"]],
      expect: [['[data-res="vdc"]', "10.8 V"], ['[data-res="ripple"]', "0.483"], ['[data-res="piv"]', "33.94 V"]] },
    { name: "example: 48 V CT PIV", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="piv"]', "67.18 V"]] },
    { name: "the load unit is remembered", do: [["set", "#rc-rload-unit", "kΩ"], ["reopen"]], expect: [["#rc-rload-unit", "kΩ"]] },
  ],
  "rectifier-bridge": [
    { name: "12 V AC, 2 × 0.7 V, 100 Ω: Vdc 9.441 V exact", do: [],
      expect: [['[data-res="vdc"]', "9.441 V"], ['[data-res="idc"]', "94.41 mA"], ['[data-res="piv"]', "16.97 V"], ['[data-res="ripple"]', "0.546"], ['[data-res="eff"]', "77%"]] },
    { name: "ideal diodes: 2Vp/π, ripple 0.483, 81.1%", do: [["set", "#rb-vf", "0"]],
      expect: [['[data-res="vdc"]', "10.8 V"], ['[data-res="ripple"]', "0.483"], ['[data-res="eff"]', "81.1%"]] },
    { name: "a peak below 2 Vf never conducts", do: [["set", "#rb-vin", "0.9"]], expect: [['[data-res="results"]', "/nothing conducts/"]] },
    { name: "example: 5 V AC", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="vdc"]', "3.19 V"]] },
    { name: "the load unit is remembered", do: [["set", "#rb-rload-unit", "kΩ"], ["reopen"]], expect: [["#rb-rload-unit", "kΩ"]] },
  ],
  "rectifier-halfwave": [
    { name: "12 V AC, 0.7 V, 100 Ω: Vdc 5.056 V exact", do: [],
      expect: [['[data-res="vdc"]', "5.056 V"], ['[data-res="idc"]', "50.56 mA"], ['[data-res="piv"]', "16.97 V"], ['[data-res="ripple"]', "1.237"], ['[data-res="eff"]', "39.5%"]] },
    { name: "ideal diode: Vp/π, ripple 1.211, 40.5%", do: [["set", "#rh-vf", "0"]],
      expect: [['[data-res="vdc"]', "5.402 V"], ['[data-res="ripple"]', "1.211"], ['[data-res="eff"]', "40.5%"]] },
    { name: "a peak below Vf never conducts", do: [["set", "#rh-vin", "0.4"]], expect: [['[data-res="results"]', "/never conducts/"]] },
    { name: "example: Schottky at 3 V AC", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="vdc"]', "1.156 V"]] },
    { name: "example: 24 V AC PIV", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="piv"]', "33.94 V"]] },
    { name: "the load unit is remembered", do: [["set", "#rh-rload-unit", "kΩ"], ["reopen"]], expect: [["#rh-rload-unit", "kΩ"]] },
  ],
  "diode-biasing": [
    { name: "forward bias conducts", do: [], expect: [[".diagram-box text:last-of-type", "conducting"]] },
    { name: "reverse bias blocks", do: [["pill", 1]], expect: [[".diagram-box text:last-of-type", "blocked"]] },
    { name: "1N4148: 1 V at 10 mA (Vishay), quoted with its current", do: [], expect: [[".card-key", "≤ 1 V at 10 mA"]] },
  ],
  "smd-package-sizes": [
    { name: "1210 is 3.2 × 2.5 mm, 0.126 × 0.098 in", do: [["set", "#sps-input", "1210"]],
      expect: [["#sps-results .card-key", "/^3.2 × 2.5 mm0.126. × 0.098.$/"]] },
    { name: "0805 is 1.25 mm wide", do: [["set", "#sps-input", "0805"]], expect: [["#sps-results .card-key", "/^2\\.0 × 1\\.25 mm/"]] },
    { name: "metric 0402 finds imperial 01005", do: [["set", "#sps-input", "01005"]], expect: [["#sps-results .formula-card-title", "/^01005 imperial · 0402 metric/"]] },
  ],
  "rl-filter": [
    { name: "100 Ω and 100 mH: fc 159.2 Hz", do: [], expect: [['[data-res="solved"]', "159.2 Hz"]] },
    { name: "at fc: −3.01 dB, 45° lag", do: [], expect: [['[data-res="db"]', "/^-3\\.01\\d* dB$/"], ['[data-res="phase"]', "/^-45° phase shift/"]] },
    { name: "example: woofer coil 509 µH", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="0"]']],
      expect: [['[data-res="solved"]', "509.3 µH"], [".pill[data-pill].active", "L"]] },
    { name: "example: choke, −16 dB at 1 MHz", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="solved"]', "159.2 kHz"], ['[data-res="db"]', "/^-16\\.\\d* dB$/"]] },
    { name: "example: RF high-pass 79.6 MHz", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="2"]']],
      expect: [['[data-res="solved"]', "79.58 MHz"], ["#rlf-topology .pill.active", "High-pass"]] },
    { name: "only real resistor units", do: [], expect: [['select[data-unit="r"]', "options:ΩkΩMΩ"]] },
    { name: "topology, solve, poles and units are remembered", do: [["click", '.pill[data-topo="highpass"]'], ["click", '.pill[data-pill="l"]'], ["set", "#rlf-poles", "2"], ["set", 'select[data-unit="r"]', "kΩ"], ["reopen"]],
      expect: [["#rlf-topology .pill.active", "High-pass"], [".pill[data-pill].active", "L"], ["#rlf-poles", "2"], ['select[data-unit="r"]', "kΩ"]] },
  ],
  "inductor-smd-code": [
    { name: "100 is 10 µH (Sumida CDRH74)", do: [["set", "#ismd-code", "100"]], expect: [['[data-res="uh"]', "10 µH"]] },
    { name: "101 is 100 µH, 102 is 1 mH", do: [["set", "#ismd-code", "102"]], expect: [['[data-res="uh"]', "1 mH"], ["#ismd-unit", "mH"]] },
    { name: "R47 is 470 nH, in nH", do: [["set", "#ismd-code", "R47"]], expect: [['[data-res="uh"]', "470 nH"], ["#ismd-value", "470"], ["#ismd-unit", "nH"]] },
    { name: "4.7 µH is stamped 4R7", do: [["set", "#ismd-unit", "µH"], ["set", "#ismd-value", "4.7"]], expect: [["#ismd-code", "4R7"]] },
    { name: "a tolerance letter is not part of the stamp", do: [["set", "#ismd-code", "10M"]], expect: [['[data-res="err"]', "/part number/"]] },
    { name: "tolerance not known: E12", do: [["set", "#ismd-code", "180"]], expect: [['[data-res="series"]', "E12 standard value"]] },
    { name: "±20% checks against E6", do: [["set", "#ismd-tol", "20"], ["set", "#ismd-code", "180"]], expect: [['[data-res="series"]', "Not in E6 — nearest is 15 µH"]] },
    { name: "no 4-digit mode", do: [], expect: [[".pill", "(missing)"]] },
    { name: "example: 4R7, ±30%", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="uh"]', "4.7 µH"], ['[data-res="tol"]', "±30%"], ["#ismd-code", "4R7"]] },
    { name: "the unit and tolerance are remembered", do: [["set", "#ismd-unit", "nH"], ["set", "#ismd-tol", "10"], ["reopen"]],
      expect: [["#ismd-unit", "nH"], ["#ismd-tol", "10"]] },
  ],
  "inductor-color-code": [
    { name: "gold as decimal point: 4.7 µH",
      do: [["click", '.roller-track[data-role="d1"] [data-color="yellow"]'], ["click", '.roller-track[data-role="d2"] [data-color="gold"]'], ["click", '.roller-track[data-role="mult"] [data-color="violet"]']],
      expect: [['[data-res="uh"]', "4.7 µH"]] },
    { name: "only inductor tolerances offered", do: [], expect: [["#ic-tol", "options:±5%±10%±20%±20%"]] },
    { name: "gold band is checked against E24", do: [], expect: [['[data-res="series"]', "E24 standard value"]] },
    { name: "bands show in their natural unit", do: [["click", '.roller-track[data-role="mult"] [data-color="red"]']],
      expect: [['[data-res="uh"]', "1 mH"], ["#ic-value", "1"], ["#ic-unit", "mH"]] },
    { name: "only real inductor units", do: [], expect: [["#ic-unit", "options:nHµHmH"]] },
    { name: "no pink multiplier on inductors", do: [], expect: [['.roller-track[data-role="mult"] [data-color="pink"]', "(missing)"]] },
    { name: "example: 4.7 µH with gold point", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="1"]']],
      expect: [['[data-res="uh"]', "4.7 µH"], ['[data-res="tol"]', "±10%"], ['[data-res="series"]', "E12 standard value"]] },
    { name: "example: MIL 5-band", do: [["click", ".example-btn"], ["click", '.example-item[data-ex="3"]']],
      expect: [['[data-res="uh"]', "3.3 µH"], [".pill.active", "5-band (MIL)"]] },
    { name: "the form and unit are remembered", do: [["pill", 1], ["set", "#ic-unit", "nH"], ["reopen"]],
      expect: [[".pill.active", "5-band (MIL)"], ["#ic-unit", "nH"]] },
  ],
};
